### ISSUE TITLE
dim attribute of matrix in 3.4

### ISSUE THREAD

**Issue by melissakey** [hadley/adv-r#1003]
just a tiny bug - the 1st MOAR diagram in 3.4 should show [2, 3], not [2, 2] 

![image](https://user-images.githubusercontent.com/24309569/38065704-a38602f8-32d2-11e8-8a5d-aff80c7a4c14.png)

should match

![image](https://user-images.githubusercontent.com/24309569/38065711-af89f4ce-32d2-11e8-9fe5-688025d96bd5.png)

**Comment by hadley** [comment]
Ooops, thanks, will be fixed momentarily!
