### ISSUE TITLE
Possible error in Functions > Lazy Evaluation example

### ISSUE THREAD

**Issue by mdpead** [hadley/adv-r#1009]
Hey Hadley,

Working through your book, I think there may be an error in the Lazy Evaluation section of the Functions page. You give an example of creating closures with lapply:

```R
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
```

And then the test the functions with:

```R
adders[[1]](10) 
## [1] 11
adders[[10]](10) 
## [1] 20
```

And say 

> x is lazily evaluated the first time that you call one of the adder functions. At this point, the loop is complete and the final value of x is 10. Therefore all of the adder functions will add 10 on to their input, probably not what you wanted!

But if this were the case you'd get:

```R
adders[[1]](10)
## [1] 20
adders[[10]](10)
## [1] 20
```

So the adder functions are actually working correctly. It looks like the environments of the adder functions contain values for x even though x wasn't evaluated:

```R
ls.str(environment(adders[[1]]))
## x :  int 1
ls.str(environment(adders[[10]]))
## x :  int 10
```

I'm not sure how / why this has happened though. I don't know if you want to tweak the example, although I can't think how, or just remove it as you have other examples of lazy evaluation. 

Thanks for the awesome book,
Matt

**Comment by mdpead** [comment]
Apologies, I've just looked at the Functions.Rmd file in the repo and you've fixed it! I was looking at http://adv-r.had.co.nz/Functions.html, should've checked the repo. Obviously as soon as the website is updated it'll be fixed there too, so I'll close the issue.

**Comment by hadley** [comment]
The WIP 2e is at http://adv-r.hadley.nz/
