### ISSUE TITLE
online version does not match github tex version

### ISSUE THREAD

**Issue by LunarLanding** [hadley/adv-r#1023]
This line is correct:
https://github.com/hadley/adv-r/blob/e38345781c25b150aacb50b289fa0259d2214451/book/tex/Environments.tex#L93

The corresponding html at http://adv-r.had.co.nz/Environments.html
is not:
![capture](https://user-images.githubusercontent.com/4441338/39305091-ca7bb5dc-4953-11e8-8f88-3616ba7811ea.PNG)

**Comment by hadley** [comment]
The tex version is the published book. You should not expect it to be in sync with the website.
