### ISSUE TITLE
Add section on how to compile R with `--enable-memory-profiling` for non Windows and mcOS users

### ISSUE THREAD

**Issue by prosoitos** [hadley/adv-r#1026]
Memory profiling support is not in R by default.

From https://cran.r-project.org/doc/manuals/R-exts.html#Profiling-R-code-for-memory-use:

> 3.3 Profiling R code for memory use
Measuring memory [...] require[s] R to have been compiled with --enable-memory-profiling, which is not the default, but is currently used for the macOS and Windows binary distributions.

Any memory profiling (e.g. section **3.3.1 tracemem()**) will not work for people not on Microsoft and macOS. A short section about having to compile R with `--enable-memory-profiling` for linux users would be nice.

**Comment by hadley** [comment]
This feels a bit specific to me — but it would be a great topic for a blog post... (hint hint)

**Comment by prosoitos** [comment]
Sounds good. Will do that :slightly_smiling_face: 
Thank you for considering!
