### ISSUE TITLE
source2 exercise in Evaluation.Rmd

### ISSUE THREAD

**Issue by osorensen** [hadley/adv-r#1082]
I have a question to [exercise 5 in Section 22.2.6](https://adv-r.hadley.nz/evaluation.html#exercises-62), which concerns keeping source references in the source2() function.

The exercise reads as follows:

> The code generated by `source2()` lacks source references. Read
    the source code for `sys.source()` and the help for `srcfilecopy()`,
    then modify `source2()` to preserve source references. You can
    test your code by sourcing a function that contains a comment. If
    successful, when you look at the function, you'll see the comment and
    not just the source code.

When I perform the test you recommend on the original `source2` function, the comments seem to be intact. Here is a minimal example, where I have used `reprex::reprex` with code on the clipboard. Interestingly, if I instead use `reprex::reprex` with the `input` file option, the code does not show in the markdown.

``` r
library(rlang)
rm(list = ls())

# Define function with comment and write to file "test.R"
writeLines(
  "f <- function() { \n # body of fn \n rnorm(10) \n }",
  con = "test.R"
)
# source2() taken from Ch. 22.2.2
source2 <- function(path, env = caller_env()) {
  file <- paste(readLines(path, warn = FALSE), collapse = "\n")
  exprs <- parse_exprs(file)
  
  res <- NULL
  for (i in seq_along(exprs)) {
    res <- eval_bare(exprs[[i]], env)
  }
  
  invisible(res)
}
# Source
source2("test.R")
# Print the function
f
#> function() { 
#>  # body of fn 
#>  rnorm(10) 
#>  }
```

**Comment by hadley** [comment]
``` r
library(rlang)

# source2() taken from Ch. 22.2.2
source2 <- function(path, env = caller_env()) {
  file <- paste(readLines(path, warn = FALSE), collapse = "\n")
  exprs <- parse_exprs(file)
  
  res <- NULL
  for (i in seq_along(exprs)) {
    res <- eval_bare(exprs[[i]], env)
  }
  
  invisible(res)
}

path <- tempfile()
writeLines(
  glue::trim("
    f <- function() { 
      # body of fn 
      rnorm(10)
    }"  
  ),
  path  
)
source2(path)
f
#> function() { 
#>   # body of fn 
#>   rnorm(10)
#> }
```

<sup>Created on 2018-12-10 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

Indeed. I can't remember why I thought this was necessary.
