### ISSUE TITLE
21.4.1: Unfinished sentence re the book's use of "expression"

### ISSUE THREAD

**Issue by russHyde** [hadley/adv-r#1096]
21.4.1_P2 / Section "Expressions::Data_Structures::Naming_Conventions"
    `We use "expression" to [unfinished description]. In base R "expression" ....`

I'd love to suggest an appropriate definition for how the books use of "expression" differs from base-R's use of expression, but I'm only reading this section for the first time.

Is the implication that you (and `rlang`) are using "expression" to refer to a single contiguous statement that may return a value, where as base-Rs use of "expression" refers to a collection of such statements. Or are you describing how these statements are represented within the language?

Regards

**Comment by hadley** [comment]
Now fixed, thanks
