### ISSUE TITLE
Adding strategy of searching errors via `searcher`/`errorist` in debug section?`

### ISSUE THREAD

**Issue by coatless** [hadley/adv-r#1098]
Consider adding a reference in the [debug chapter](https://adv-r.hadley.nz/debugging.html) to:

- [`searcher`](https://github.com/coatless/searcher): Query Search Portals from R 
- [`errorist`](https://github.com/coatless/errorist): Automatic Error and Warning Search

These packages make it easy to instantly searcher errors that occur while programming. 

In particular, the `searcher` package is designed to allow users to take the last error message and launch a search in a web browser using either Google, Bing, DuckDuckGo, ixquick, StackOverflow, GitHub, and BitBucket. 

Meanwhile, `errorist`, will take either the last error message or **warning** and automatically search it using one of the predefined portal above when an issue is detected.

**Comment by hadley** [comment]
I'll mention how important it is to google for errors, and then mention these packages as ways of automating the process.
