### ISSUE TITLE
R6 Inheritance exercise discusses private members before main text introduces them

### ISSUE THREAD

**Issue by daniel-barnett** [hadley/adv-r#1133]
In Section 16.2.6 (R6 Classes and methods exercises, https://github.com/hadley/adv-r/blob/master/R6.Rmd#exercises), the question asks whether private members are inherited, however at that point the only thing we've seen on private/public members is "Later, we’ll see how to use private fields and methods to prevent casual access to the internals of your class." at the end of section 16.2.

**Comment by hadley** [comment]
oops, thanks!
