### ISSUE TITLE
explain attribute retention using subsetting, not dplyr::mutate

### ISSUE THREAD

**Issue by maxheld83** [hadley/adv-r#1148]
(This is jumping off of #1147).

Attribute retention seems like an important S3 issue to me.

Maybe especially with the spread of idempotent functions in the tidyverse.
(I read somewhere that attributes were originally dropped in R, because the FP assumption was that functions would mostly return *different* objects, as e.g. the apply family occasionally does).

The book currently discusses this with regard to `dplyr::mutate()` and lays out a nice way to do this via `sloop::reconstruct()`.

However, I'm wondering whether this (attribute retention) might be better explained using a more mainstream function, such as subsetting.
The dplyr example might make some readers gloss over it, considering this a special case, when it's really happening all over R.

I'd also appreciate your thoughts on whether this (teaching R to retain attributes) is a good idea, and if so, when. 

I'd be happy to draft a PR, but wanted to check back first.

Would also be good to know in how far users can rely on (yet unreleased) `sloop::reconstruct()`.

Related stuff / thoughts:
- [SO question](https://stackoverflow.com/questions/9486342/subset-drops-attributes-on-vectors-how-to-maintain-persist-them)
- [community.rstudio.com question](https://community.rstudio.com/t/how-can-i-retain-attributes-from-an-s3-class-on-subsetting-and-should-i)
- [newish package sticky](https://github.com/decisionpatterns/sticky) which makes a bunch of generics retain attributes via a new `sticky` class (I think?)

**Comment by hadley** [comment]
I don't really understand the question, sorry. Can you provide more details?

**Comment by maxheld83** [comment]
Sorry for being verbose/unclear.

I just thought that perhaps, reconstruct classes might be easier explained with a simpler / more mainstream function, such as subsetting.
At first, I glossed over your discussion of reconstruction, because I thought this somehow only applied to `dplyr::mutate()`, which of course it wasn't.

Also would appreciate some advice on when/how reconstruction (~ retaining attributes) is advisable. 

My lay understanding of the focus of type stability / idempotence in the tidyverse led me to think that perhaps, retaining attributes should make more sense for more classes (or fields thereof) now. Then again, it alway really depends which fields can be reconstructed/retained, so I'd be happy to read your guidance on that. 

If this doesn't make sense to you, feel free to close – I might just have this all wrong, it's happened before 😅.

**Comment by hadley** [comment]
I think this is now more clearly out of scope for advanced R. Here I'll focus on how the OO systems work. If you want to define a new class (that automatically preserves attributes), you should use `vctrs::new_vctr()`. I'm still working on the docs, but you can see a bunch of reasonable realistic examples at <https://vctrs.r-lib.org/articles/s3-vector.html>
