### ISSUE TITLE
Link to "Translate" chapter does not work in intro.

### ISSUE THREAD

**Issue by EdwinTh** [hadley/adv-r#1150]
In the [intro to metaprogramming chapter](https://adv-r.hadley.nz/meta.html) there is a summing up of the four subsequent chapters, with their links. For the final chapter Translating R code the link is not working, but it shows [Translation]. 

Was looking to do a PR, but I can't figure out why it isn't working myself.

**Comment by hadley** [comment]
Seems to be working now
