### ISSUE TITLE
Image not showing in "Non-standard evaluation"

### ISSUE THREAD

**Issue by ismayc** [hadley/adv-r#1158]
It looks like the image has been moved? http://adv-r.had.co.nz/temp_files/figure-html/plot-labels-1.png

![screenshot 2018-08-15 09 20 09](https://user-images.githubusercontent.com/9215614/44163287-d2069800-a077-11e8-9473-bb56057834b9.png)

**Comment by hadley** [comment]
All the images in the 1st edition are broken 😢

**Comment by hadley** [comment]
Will fix as part of #798
