### ISSUE TITLE
Spell checking

### ISSUE THREAD

**Issue by jeroen** [hadley/adv-r#1166]
To run a spell check on all `Rmd` files:

```r
spell_check_files(list.files(pattern=".Rmd"), lang = 'en-GB')
```

Mostly false positives but a few hits:

```
  WORD                   FOUND IN
absense                base-types.Rmd:117
analog                 beyond-exception-handling.Rmd:271
                       Functionals.Rmd:478
arugment               Evaluation.Rmd:499
attibute               Translation.Rmd:176
...
```

We can also automate this if you'd like.

**Comment by hadley** [comment]
Hmmm, I kind of like fixing spelling mistakes as an easy intro to doing a PR with github. But would be worth doing prior to release.

**Comment by hadley** [comment]
@jeroen has anyone plumbed this up with rstudioapi to automatically jump to the correct line?

**Comment by jeroen** [comment]
No not yet. If I remember correctly there was an [unsolved issue](https://github.com/ropensci/spelling/pull/3#issuecomment-342169864) with getting the source line numbers from roxygen2 comment documentation, so we are still spelling checking from the `.Rd` files.

**Comment by jeroen** [comment]
Actually that only holds for the manual documentation, perhaps this doesn't matter for markdown files. Anyway afaik no rstudioapi support yet.
