### ISSUE TITLE
6.6.1. Implicit vs Explicit returns - calling functions that don't exist

### ISSUE THREAD

**Issue by data-al** [hadley/adv-r#1172]
In chapter: **"6.6.1. Implicit vs Explicit returns"**, the example function is the following:

```
j01 <- function(x) {
  if (x < 10) {
    0
  } else {
    10
  }
}
```

but when calling the created function to demonstrate implicit return instead of the following:

```
f(5)
#> [1] 52
f(15)
#> [1] 452
```

there should be:

```
j01(5)
#> [1] 0
j01(15)
#> [1] 10
```

?

**Comment by hadley** [comment]
Seems fine now: https://adv-r.hadley.nz/functions.html#implicit-vs.explict-returns
