### ISSUE TITLE
could not find function "env_print" (from Environments.Rmd)

### ISSUE THREAD

**Issue by miguelmorin** [hadley/adv-r#1173]
I updated all packages with the method in [this thread](https://www.r-bloggers.com/update-all-user-installed-r-packages-again/). I also installed `bookdown`. I launch the building of the book from `adv-r.Rproj` within RStudio and I get

```
Quitting from lines 117-119 (Environments.Rmd) 
Error in env_print(e1) : could not find function "env_print"
Calls: local ... handle -> withCallingHandlers -> withVisible -> eval -> eval
Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile Environments.Rmd
Calls: <Anonymous> ... render_book -> render_new_session -> Rscript_render
Execution halted

Exited with status 1.
```

I added
```
library(rlang)
env_print(e1)
```
at lines 117-118 of `Environments.Rmd` with the same result. I also upgraded R to the latest version, `3.5.1`.

**Comment by hadley** [comment]
You need the dev version of rlang

**Comment by miguelmorin** [comment]
Yes, I confirm, thank you!

**Comment by hadley** [comment]
I also put all the package versions at https://adv-r.hadley.nz/introduction.html#colophon

**Comment by miguelmorin** [comment]
I added the production and development packages and successfully built the book. Thanks!
