### ISSUE TITLE
find_assign_call function in Expressions chapter does not capture assignments of the form "a" <- 1

### ISSUE THREAD

**Issue by drtjc** [hadley/adv-r#1176]
The find_assign_call function is:
```{r}
find_assign_call <- function(x) {
  if (is_call(x, "<-") && is_symbol(x[[2]])) {
    # more code
}
```
The `is_symbol` check means that assignments of the form `"a" <- 1` (as opposed to `a <- 1`) are not captured.

I assign the copyright of this contribution to Hadley Wickham.

**Comment by hadley** [comment]
I think that's ok. It's a teaching example and is not meant to be comprehensive.  But maybe this would make a good exercise!

**Comment by drtjc** [comment]
seems sensible. Thanks for the response.
