### ISSUE TITLE
3.7 Q2

### ISSUE THREAD

**Issue by ktang** [hadley/adv-r#1179]
In https://adv-r.hadley.nz/names-values.html#names-values-answers  
Q2: The code gives the size of y is  8,000,128 B, but the text is "It occupies about 4 MB.".
In my understanding, 8,000,128 B is about 8 MB. 
Is the "4 MB" a typo?
Thanks a lot!

**Comment by hadley** [comment]
Yup, it's a typo

**Comment by ktang** [comment]
Hi Hadley,
Thank you so much for your reply. I have created a pull request to fix the typo.
Best regards,
Kai
