### ISSUE TITLE
Web page buglet

### ISSUE THREAD

**Issue by eddelbuettel** [hadley/adv-r#118]
From IM:
Just tried to pry a trick or two from your adv-r webpage ... and noticed a BUG in the css / js / twitter bootstrap
On a wide screen (at work) scrolling down makes the 'learn in person' well run over the empty column and in the 'welcome' text
browser is chrome 30.0.1599....
[...]
Resolution is 1920x1200
That said my ultrabook is also 1600x900 and it is also fscked up
the well widens into the empty sep. column

**Comment by hadley** [comment]
Will be moving to bookdown in the near future

**Comment by eddelbuettel** [comment]
An intention to make change is not a fix.  So if it isn't fixed, why close it?
