### ISSUE TITLE
Inconsistency in description of R's age

### ISSUE THREAD

**Issue by gvwilson** [hadley/adv-r#1186]
https://adv-r.hadley.nz/introduction.html says both:

- "You are confronted with over 20 years of evolution every time you use R."

and:

- "R is still a relatively young language."

which feels as if being twenty is implicitly being called a long time, but then being called short.

**Comment by hadley** [comment]
Second sentence is now:

> Because the R community mostly consists of data scientists, not computer scientists, there are relatively few books that go deep in the technical underpinnings of R.
