### ISSUE TITLE
Error in new_subclass constructor in S3 chapter?

### ISSUE THREAD

**Issue by drtjc** [hadley/adv-r#1191]
The code in the S3 chapter, Inheritance, Constructors, is:
```
new_subclass <- function(x, y, z) {
  stopifnot(is.character(z))
  new_my_class(x, y, z, subclass = "subclass")
}
```
Constructing a `new_subclass` results in an error:
```
new_subclass(1:3, TRUE, "test")
#  Error in attributes(.Data) <- c(attributes(.Data), attrib) : 
#  all attributes must have names [2 does not] 
```
Should the call to `new_my_class` in `new_subclass` contain `z = z` rather than just `z`?
```
new_subclass <- function(x, y, z) {
  stopifnot(is.character(z))
  new_my_class(x, y, z = z, subclass = "subclass")
}
```

I assign the copyright of this contribution to Hadley Wickham.

**Comment by hadley** [comment]
Ooops yes, want to do a PR?

**Comment by drtjc** [comment]
ok, let me just figure out how to do it!
