### ISSUE TITLE
Error in subclass coercion to parent class in S3 chapter?

### ISSUE THREAD

**Issue by drtjc** [hadley/adv-r#1192]
The code in the S3 chapter, Inheritance, Coercion, is:

```
as_my_class.sub_class <- function(x) {
  new_my_class(attr(x, "x"), attr(x, "y"))
}
```
This gives an error when used. Should this be:
```
as_my_class.sub_class <- function(x) {
  new_my_class(x, attr(x, "y"))
}
```
Also, this code still leaves the `z` attribute on the `x` object, even though the subclass is stripped. I'm wondering what would be considered best practice here? It could easily be removed with something like:

```
as_my_class.sub_class <- function(x) {
  pc <- new_my_class(x, attr(x, "y"))
  attr(pc, "z") <- NULL
  pc
}
```

I assign the copyright of this contribution to Hadley Wickham.

**Comment by hadley** [comment]
I think this needs to be rewritten in light of recent work in the vctrs package. I'll tackle that when I next look at this chapter
