### ISSUE TITLE
S3 chapter, internal generics: is y object undefined?

### ISSUE THREAD

**Issue by drtjc** [hadley/adv-r#1199]
In the code below, what does `y` refer to? Is doesn't seemed to be defined earlier in the chapter but I could have missed it.
```
x <- sample(10)
class(x)
#> [1] "integer"
s3_dispatch(x[1])
#>    [.integer
#>    [.numeric
#>    [.default
#> -> [

class(y) 
#> [1] "numeric"
s3_dispatch(mtcars[1])
#> -> [.data.frame
#>    [.default
#>  * [
```

In understanding your point that internal generics do not dispatch to methods unless the class attribute has been set I wrote the simple example below. If you think it is useful I could PR it.

```
x <- 1:2
s3_dispatch(x[1]) # [.integer is top of dispatch list

class(x) # integer
attributes(x) # note that there is no class attribute even though x has a class
is.object(x) # not an object

# define [.integer method
`[.integer` <- function(x, y) "hi"
x[1] # 1 ## [ does not dispatch to [.integer, internal generic `[` is called directly

# turn x into an object
attr(x, "class") <- "integer" # assign class attribute of integer
attributes(x) # there is now a class attribute
is.object(x) # now an object
x[1] # hi ## since x is now an object, [ dispatches to [.integer
```
 
I assign the copyright of this contribution to Hadley Wickham

**Comment by hadley** [comment]
It looks like `s3_dispatch()` isn't doing the right thing here:

``` r
library(sloop)

`[.integer` <- function(x, y) "hi"
x1 <- 1:5
s3_dispatch(x1[1])
#> -> [.integer
#>    [.numeric
#>    [.default
#>  * [

x2 <- structure(x1, class = "integer")
s3_dispatch(x2[1])
#> -> [.integer
#>    [.default
#>  * [
```

<sup>Created on 2018-10-03 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

I'd rather fix that and then allow people to explore on their own. Might make for a good exercise

**Comment by hadley** [comment]
Thanks for spotting this!
