### ISSUE TITLE
Remove CXXR reference or mention name change and suspension of development?

### ISSUE THREAD

**Issue by hammer** [hadley/adv-r#1242]
CXXR was [renamed to Rho](
https://groups.google.com/forum/m/#!topic/rho-devel/tfOintCKVNo), and Rho has [suspended development](
https://github.com/rho-devel/rho/commit/bf6c652b826cd892e88630eb35f182b614af52b1). It may be worth noting these developments in the Performance chapter.

**Comment by hadley** [comment]
Thanks — I haven't rewritten any of the chapters in the techniques section yet, but will probably do so in November. The plan for October is to do another pass through the metaprogramming and OOP parts.
