### ISSUE TITLE
Example re: how to specify default function arguments

### ISSUE THREAD

**Issue by jennybc** [hadley/adv-r#1248]
`abind::abind()` has this signature:

``` r
abind(..., along=N, <more args>)
```

where `along` is "(optional) The dimension along which to bind the arrays. The default is the last dimension, i.e., the maximum length of the dim attribute of the supplied arrays."

Good as example or exercise exploring the relative merits of different default strategies. Seems that `along = NULL` would have been easier to program around / wrap & expose.

**Comment by hadley** [comment]
Because then there would be more room for design discussion and alternatives
