### ISSUE TITLE
Write about delayed S3 method registration (R >= 3.6.0)

### ISSUE THREAD

**Issue by helix123** [hadley/adv-r#1258]
R >= 3.6.0 (currently devel) introduced delayed S3 method registration (https://cran.r-project.org/doc/manuals/r-devel/R-exts.html#Registering-S3-methods).

Would be nice to have a more elaborated coverage of that topic incl. an example in adv-r!

**Comment by hadley** [comment]
This will happen in https://github.com/r-lib/vctrs/issues/113 — adv-r simply doesn't have enough room to deal with the intersection of S3 and packages.
