### ISSUE TITLE
Current planings for exercise rewrites?

### ISSUE THREAD

**Issue by Tazinho** [hadley/adv-r#1259]
Hi Hadley, do you currently plan any systematic or larger rewrites of exercise sections?

We currently have two problems with Advanced R Solutions.
1. It is hard to sync the exercises between the books.
2. Solved exercises might be dropped or changed afterwards on your end.

To minimize this overhead a bit, it would definitely help us know, if any section can be expected to change a lot in the next weeks.

Thanks in advance.

**Comment by hadley** [comment]
There should be relatively little churn in foundations and functional programming. I should be finished with my second pass through OOP in <2 weeks, and exercises will be largely stable after that. I'll then work on metaprogramming, and finally techniques.
