### ISSUE TITLE
(ambiguous) Exercise 2.5.3.1 - Why would two functions be needed?

### ISSUE THREAD

**Issue by henningsway** [hadley/adv-r#1292]
Exercise [2.5.3.1](https://adv-r.hadley.nz/names-values.html#exercises-3) asks to "_Wrap the two methods for subtracting medians into two functions_, then use the bench (Hester 2018) package to carefully compare their speeds."

I wonder why two different functions would be needed. When I look at the example in the book I see
some data-generation.

    x <- data.frame(matrix(runif(5 * 1e4), ncol = 5))
    medians <- vapply(x, median, numeric(1))

a conversion of the data structure

    y <- as.list(x)

and the computation of the median

    for (i in seq_along(medians)) {
      x[[i]] <- x[[i]] - medians[[i]]
    }
    
    for (i in 1:5) {
      y[[i]] <- y[[i]] - medians[[i]]
    }

which seem the same for both lists and dataframes.

When answering this question, I would prepare the data generation and the list-conversion and than call the same wrapper for the subtact-median-function on `x` and `y`.

Would there be advantages to constructing two wrappers? And what should they (kind of) look like?

**Comment by hadley** [comment]
The functions should both input and output a data frame, so one is going to need to do a bit more work.
