### ISSUE TITLE
3rd diagram in "3.5.1 Creating" not quite right

### ISSUE THREAD

**Issue by prosoitos** [hadley/adv-r#1298]
Sorry for yet another diagram issue... :\

![image](https://user-images.githubusercontent.com/4634851/47612716-59d82d80-da3d-11e8-8f6c-e81ccc898c46.png)

![image](https://user-images.githubusercontent.com/4634851/47612712-475df400-da3d-11e8-9452-255b38bf151a.png)

![image](https://user-images.githubusercontent.com/4634851/47612718-6ceafd80-da3d-11e8-88cb-68c41301c47e.png)

If I understand correctly, to be consistant in the diagram representation, I think that the above diagram has 2 little problems:

- the boxes around `3` and `4` should touch each other to form a vector
- the 2nd layer of boxes around `1` and `2` should also touch each other to form a list of 2

**Comment by hadley** [comment]
Thanks!  (For future reference, I have no idea what section corresponds to what number, so the section name is much more helpful for me)

**Comment by prosoitos** [comment]
Oh, you had actually mentioned this to me before and I forgot. Sorry! Will try to remember it for next time!!
