### ISSUE TITLE
Suggestion: make the example and the diagram match each other in "3.6 Data frames and tibbles"

### ISSUE THREAD

**Issue by prosoitos** [hadley/adv-r#1299]
In the intro section of "3.6 Data frames and tibbles", the diagram does not match the example explored just before.

Not a mistake, but it would be nicer and facilitate the visualization and understanding of the reader if the diagram matched the example that has just been covered (even if I realize that the diagram is only there to explain the schematic representation of data frames).

If this sounded reasonable, since changing the example is less time consuming than changing the diagram, maybe `data.frame(x = 1:2, y = 2:1)` could be replaced by `data.frame(x = 1:3, y = letters[1:3])` (and the same for the tibble example).

Unless of course there is a good reason that I am missing to use that particular example.

**Comment by prosoitos** [comment]
Note: I would be happy to make this little change in a PR.

**Comment by hadley** [comment]
Changing the code sounds great, thanks!

**Comment by prosoitos** [comment]
Great. I'll submit a PR today.

**Comment by prosoitos** [comment]
Done
