### ISSUE TITLE
Provide Hint for "Object Size" Question

### ISSUE THREAD

**Issue by henningsway** [hadley/adv-r#1303]
I am currently trying to work through the book and solve most of the exercises. I'm a little stuck with one last question from the Names and Values chapter. Specifically one from 

https://adv-r.hadley.nz/names-values.html#object-size

_2. Take the following list. Why is its size misleading?_

`x <- list(mean, sd, var)`
`obj_size(x)`
`#> 17,664 B`

I have compared the elements sizes with `object.size`, looked at the code of these functions (which seem to share some common parts) and thought about shared values. But somehow I'm a little stuck and would like to move on.

Could you provide a hint, how to best approach this? :)

**Comment by hadley** [comment]
Hmmm, I can't think of a good hint — the point is that `mean` etc are all built-in to R. How should you consider their size?

**Comment by henningsway** [comment]
Will give it another shot, thanks!
