### ISSUE TITLE
pryr::object_size() vs. lobstr::obj_size()

### ISSUE THREAD

**Issue by Tazinho** [hadley/adv-r#1324]
I am currently trying to finalize exercise 3 from the "Object size" section in the "Names and values" chapter.

However, I am having difficulties since `pryr::object_size()` and `lobstr::obj_size()` return different values, which becomes already relevant while answering the first part of the question.

__Q__: Predict the output of the following code:

```r
x <- 1:1e6
obj_size(x)
```

__A__: So in a fresh packrat project with both devversions installed I am getting on Windows 10 and R 3.5.1

```r
x <- 1:1e6
unclass(pryr::object_size(x))
#> [1] 4000048
lobstr::obj_size(x)
#> 680 B
```

For me it is not clear which result is correct and if there is sth. missing in the chapter to explain this behaviour.

From the current text in the book the result from __pryr__ makes sense to me as it is consistent with all your previous explanations (48 + 8 * 1000000). However, there might be some changes in R (maybe ALTREP) that only __lobstr__ is aware of and which are currently not mentioned in the book.

A short test which takes away the ordering of `x` strengthens this assumption:

```r
y <- sample(1:1e6)
unclass(pryr::object_size(y))
#> [1] 4000048
lobstr::obj_size(y)
#> 4,000,048 B
```

So maybe this issue should be called 'Mention ALTREP in "Names and values"'. However, also an issue in __pryr__ might be appropriate.

(Of course, we could try to tackle this exercise without further information. However, I guess this change in the exercise might not be intended. Clarification would be appreciated anyway).

**Comment by hadley** [comment]
Yeah, this is an altrep issue.

**Comment by hadley** [comment]
It looks like I changed this exercise already (to use `runif()` instead of `:`), but I'll also highlight this issue in the text.

**Comment by Tazinho** [comment]
Would it make sense to you to switch to `x <- sample(1e6)` or any other integer vector for `x` again? The reason ist that otherwise a part of the exercise would get lost: In particular in the 3rd block of the following code (in the line `y[[1]][[1]] <- 10`) the silent type conversion from integer would be dropped.

```
x <- runif(1e6)
obj_size(x)

y <- list(x, x)
obj_size(y)
obj_size(x, y)

y[[1]][[1]] <- 10
obj_size(y)
obj_size(x, y)

y[[2]][[1]] <- 10
obj_size(y)
obj_size(x, y)
```

**Comment by hadley** [comment]
The intent is not to think about type coercions here, that would be a bit subtle and there's a bunch of other stuff going on.
