### ISSUE TITLE
Emoji not showing

### ISSUE THREAD

**Issue by prosoitos** [hadley/adv-r#1337]
I noticed `r emoji("world_map")` in Functionals.Rmd file (in textbox of `8.2 My first functional: map()`).

But no emoji is showing (qutebrowser or Chromium) and that creates a space before the `?`

**Comment by hadley** [comment]
Looks fine to me

<img width="802" alt="screenshot 2018-12-10 at 8 55 21 am" src="https://user-images.githubusercontent.com/4196/49740193-54cfe600-fc59-11e8-8d9c-56ca21c24139.png">

I checked in safari, chrome, and firefox.

**Comment by prosoitos** [comment]
OK. I can't see it, no matter what browser I use. I am on Arch Linux and I must be missing an emoji library or something like that.

Sorry for the noise. I thought of checking several browsers, but I didn't think of checking on another machine.
