### ISSUE TITLE
How to customize code highlighting to match style of Advanced R book?

### ISSUE THREAD

**Issue by henningsway** [hadley/adv-r#1338]
I really like the reduced and clear highlighting the book uses for it's code chunks. I've been trying to transfer the appearance for [advanced-r-solutions.rbind.io](https://advanced-r-solutions.rbind.io) 

It seems, the modifications are specified in 'www/highlight.css' - but I don't see, where this information is passed to bookdown/rmarkdown/pandoc?

I have the feeling, I may be missing sth obvious here? :)

**Comment by hadley** [comment]
I have no idea 😢

**Comment by hadley** [comment]
There's https://github.com/hadley/adv-r/blob/master/_output.yml#L11 but that doesn't seem to be related to syntax highlighting.

But are you sure the styles are different? I just took a quick look at the solutions and the style formatting looks the same to me.

**Comment by henningsway** [comment]
Thank you for taking a look.

I believe, there are subtle differences, even though we use the default syntax highlighting also.
For example the second exercise in the Vectors Chapter.

![image](https://user-images.githubusercontent.com/1403304/49895446-b7d79d80-fe50-11e8-8e09-5af1d7c453a7.png)
(Advanced R)

![image](https://user-images.githubusercontent.com/1403304/49895402-9e365600-fe50-11e8-9a77-495c82e9dcfc.png)
(Advanced R Solutions)

I will tackle this another day, though! :)
