### ISSUE TITLE
9.2 "My first functional: map()" exercise 7 bad format

### ISSUE THREAD

**Issue by dongzhuoer** [hadley/adv-r#1391]
![image](https://user-images.githubusercontent.com/15871952/50470522-ccd53480-09eb-11e9-83e6-80e6827ce2ff.png)

**Comment by hadley** [comment]
The source and pdf output look fine; I think this must be an issue with mathjax in the html rendering.

**Comment by hadley** [comment]
Hmmmm, but the math in function factories looks fine: https://adv-r.hadley.nz/function-factories.html#MLE

**Comment by hadley** [comment]
Hmmm and now https://adv-r.hadley.nz/functionals.html#exercises-28 looks fine to me too. It's possible that if you're in China the problem is the mathjax CDN.

**Comment by dongzhuoer** [comment]
Yeah, I use a proxy and it looks fine now.
