### ISSUE TITLE
Add section on NA?

### ISSUE THREAD

**Issue by prosoitos** [hadley/adv-r#1399]
Unless I missed something, the concept of NA is not explicitly introduced anywhere in the book. In chapter "Vectors", section "Atomic vectors", sub-section "Scalars", you mention NA of the 4 main data types, but without much explanations.

A colleague trying to get a deeper understanding of R by reading this book got extremely confused by this section. This made me think that this kind of info might be very useful to add:

---

- In R's outputs, all NAs appear as `NA`, regardless of their type:

``` r
NA_integer_
#> [1] NA

typeof(NA_integer_)
#> [1] "integer"
```
- We often replace missing data by `NA` (the missing value for logicals) and this usually works since logicals can be coerced to any other data type:

``` r
v <- c("string1", "string2", NA)

typeof(NA)
#> [1] "logical"

typeof(v[3])
#> [1] "character"
```
For both of these reasons, you might not have been exposed to the explicit notations of NAs of the types character, double, or integer.

When NAs don't get coerced from logical to the suitable data type, these notations come in handy and let you avoid having to use the `as.*()` functions: `NA_integer_` is nicer than `as.integer(NA)`.

---

Note 1: this is my understanding, but please correct me if I am wrong somewhere

Note 2: if you think that adding more info on NA would indeed be a good thing, I would be happy to submit a PR transforming the scalars sub-section a bit, adding this info, and moving it after the coercion section.

**Comment by hadley** [comment]
Agreed — I think it should probably be a new section after "scalars", and also needs to mention `NA == NA` and `is.na()`

**Comment by prosoitos** [comment]
Cool. Thank you for being open to the suggestion.

I am personally not a huge fan of the "scalar" section since scalars don't exist in R and I'd much rather talk about vectors of length one. Beyond being more "proper", I find it more useful to understand the fundamental importance of vectors in R as a basal building block.

The idea of moving the NA section after the "coercion" section is that part of the info involves the concept of coercion (my little blurb above does require some understanding of coercion). As I understand it, if we can get away with filling all missing values in a data set with NAs without worrying about their data type, it is thanks to coercion.

Anyhow, I will think this through carefully and submit a PR tomorrow. I will try to break it down into several commits to make it easier for you to discard some of my suggested changes you don't like while keeping others.
