### ISSUE TITLE
Techniques Chapter: Python Interface

### ISSUE THREAD

**Issue by jtelleria** [hadley/adv-r#1410]
The Second Edition of "Advanced R" seems to have left behind the "C Language Interface" (In favor of Rcpp), however:

- I would create a last chapter which presents the "Python reticulate" Interface, and its integration with R. At the end, there are really good packages in Python such as "statsmodels", "keras", "scikit-learn" from which the R Community can benefit of.
- Some very basic notions of the "C Interface" (e.g: Data Types), and some references to get further insights on such C Language Interface.

**Comment by hadley** [comment]
Unfortunately both of those are now out of scope because the book is basically content complete (and will be sent for publication soon)
