### ISSUE TITLE
Another bug and some comments about "21 Translating R code"

### ISSUE THREAD

**Issue by juangomezduaso** [hadley/adv-r#1431]
1)
https://github.com/hadley/adv-r/blob/57ee011bc9aaff5b76ce985113cb7be9356e58b4/Translation.Rmd#L35
Ist says: "This chapter together pulls together many techniques discussed elsewhere in the book."
and should be: "This chapter pulls together many techniques discussed elsewhere in the book."
2)
In "21.2 HTML" it is said, about HTML, that:
 "It’s a special case of SGML (Standard Generalised Markup Language), and it’s similar but not identical to XML (eXtensible Markup Language)"
I think that this can be misleading about the different roles and levels of abstraction that XML and HTML have. In my opinion, it would be more accurate to say something like: "it was originally defined in SGML Standard Generalised Markup Language), but in it's more recent versions, like HTML5, it is an XML based language".
Old html didn't necesarily have the strictly nested nature of XML languages. That caracteristic, mentioned in the following paragraph of the book, makes this example viable. Old html documents  "looseness" would make them much more difficult to produce from a functional translation from R like the one shown in this interesting and inspiring chapter!
I assign the copyright of this and every other contribution that I may do to this project to Hadley Wickham

**Comment by hadley** [comment]
For minor typos, can you please do a pull request by clicking the edit button at the top of each chapter?

I don't think going into additional detail about the history of HTML really adds anything here.

**Comment by juangomezduaso** [comment]
Sorry. I will do it if I find any more typos. Tried it but it required me to do a fork and I was lazy for what I thought would be just one little bug. 
I agree that history of html isn't interesting at all here. But, well, you asked for trouble mentioning SGML (which I had almost forgotten about)  ;)
Now seriously, my text was  needlesly complicated, I agree.
But regarding  XML and HTML being "similar but not identical" .... hummm  I would change that indeed.
