### ISSUE TITLE
T,F perils

### ISSUE THREAD

**Issue by juangomezduaso** [hadley/adv-r#1443]
https://github.com/hadley/adv-r/blob/b1bc76458127731690246caf5c94bc849d66ffca/Vectors.Rmd#L108
Would it be worth it to add a footnote here reminding that T and F are just assigned aliases, not reserved words of the language?
It is "tempting", and possible, to choose the name F to ones function, but a really bad idea

**Comment by hadley** [comment]
I honestly don't consider reassigning `T` or `F` to be a threat that needs to be explicitly called out.
