### ISSUE TITLE
in defense of x[which(y)]

### ISSUE THREAD

**Issue by juangomezduaso** [hadley/adv-r#1444]
https://github.com/hadley/adv-r/blob/b1bc76458127731690246caf5c94bc849d66ffca/Subsetting.Rmd#L735
Well, I suppose it didn't fit into the name ;), but the help page of which() is entitled "Which elements are TRUE?" (and one has to read "are TRUE" as "are undoubtedly true"). 
I am guilty of what you say here, I use to make selections with this filtering-mapping function when I need it's clear and straightforward behavior wrt NAs ( similar to dplyr::filter() ).
I prefer x[which(y)] to the alternative: x[!is.na(y)&y] that is longer, relatively more error prone, and forces the reader to parse the expression to get the intent. And these 3 drawbacks increase in case y is not a name but a logical expression.
Viewing it from this angle, I think that which() inside the subsetting brackets is an idiom very much in the spirit of the tidyverse ;)

**Comment by hadley** [comment]
I still don’t think it’s a good idea, sorry.
