### ISSUE TITLE
Possibly mention Advanced R Solutions in Introduction?

### ISSUE THREAD

**Issue by henningsway** [hadley/adv-r#1471]
It's great to see the second edition of Advanced R moving towards publication. Lagging a little behind, we have also been busy improving the content of [advanced-r-solutions.rbind.io](advanced-r-solutions.rbind.io).

Obviously the solutions are still work in progress, but I was wondering, if you would consider mentioning the solutions in Advanced R. Maybe as part of [https://adv-r.hadley.nz/introduction.html#getting-help](https://adv-r.hadley.nz/introduction.html#getting-help) or so. :-)

**Comment by hadley** [comment]
Oh yes, definitely!
