### ISSUE TITLE
On using OOP effectively

### ISSUE THREAD

**Issue by p0bs** [hadley/adv-r#1475]
I'm looking forward to getting my hands on the next edition of the book; so much so that I've grazed the site of the latest draft. It looks excellent.

One other (far smaller) point of feedback regards your decision to avoid any mention of the effective use of OOP. I understand the reasoning that you give near the start of section 3:

> This book focusses on the mechanics of OOP, not its effective use, and it may be challenging to fully understand if you have not done object oriented programming before. You might wonder why I chose not to provide more immediately useful coverage. I have focussed on mechanics here because they need to be well described somewhere (writing these chapters required a considerable amount of reading, exploration, and synthesis on my behalf), and using OOP effectively is sufficiently complex to require book-length treatment; there’s simply not enough room in Advanced R to cover it in the depth required.

Whilst I recognise that there isn't enough room to cover it in the depth required, is there any way of you signposting readers to somewhere that will help them use OOP more effectively? Or would you be able help readers on their way by providing your top ten tips (of many) on the effective use of OOP? 

I recognise that I'm saying this from a position of huge relative ignorance, but thought it might help you to ask the question from a keen reader's perspective.

Many thanks for a great book.

**Comment by hadley** [comment]
Such work is likely to appear at http://principles.tidyverse.org/ at some point in the next 2 (?) years.
