### ISSUE TITLE
Minor typos

### ISSUE THREAD

**Issue by jhrcook** [hadley/adv-r#1479]
Thank you for this book along with all of your other writings (eg. *R for Data Science*, and *R Packages*). Here are a few typos I found over the past few weeks:

---

**Section 18.5.1:** "Let’s first the type of `T` vs. `TRUE`:"

**Section 20.6 Intro:** "I’ll use this technique to motivate how quasiquotation and (regular) evaluation can help you *write wrappers such functions.*"

**Section 20.5.3:** "*It’s not possible to evaluate `expr` only the data mask*, because the data mask doesn’t include any functions like `+` or `==`."

---

\- Josh Cook

**Comment by hadley** [comment]
Would you like to make a PR? You can just click the edit link at the top of each page and make the changes directly.

**Comment by jhrcook** [comment]
If that's easier for you, then I'll take care of that in the next few days.

\- Josh Cook
