### ISSUE TITLE
eval_bare() or eval()

### ISSUE THREAD

**Issue by juangomezduaso** [hadley/adv-r#1527]
In my opinion, 20.2.1 switches somewhat "abruptly" from eval() to eval_bare(). As far as I could see, eval() is the one mentioned in all previous chapters (besides eval_tidy which was also presented when first used). I understand that they are similar and perhaps you dont want to show the distinction here, but I would be more confortable if there were at least one sentence introducing it.
Furthermore, 20.2.2 refers to both stating that:
"We can create a simple version of source() by combining eval() with parse_expr() from Section 18.4.3. We read in the file from disk, use parse_expr() to parse the string into a list of expressions, and then use eval_bare()"
But then, just eval() is actually used in the code below.
The same happens in 20.2.3, where the text refers to eval_bare() but the example is made using eval()

**Comment by hadley** [comment]
Thanks for spotting that - an earlier version used `eval_bare()` instead of `eval()` and I clearly missed a few changes.
