### ISSUE TITLE
S3 Scalar object validation

### ISSUE THREAD

**Issue by DavisVaughan** [hadley/adv-r#1553]
With a scalar object, `x` is generally a list of known inputs. Take `new_lm()` as an example, where `x` would be a list of 12 known inputs.

Should `new_lm()` validate that `x` has (at least) those 12 named inputs? Or should it just validate that `x` is a list?

Should it validate both the names of the 12 inputs, and the types?

Or is this the job of `validate_lm()` (I don't think so, personally)?

So, should the coefficient checks be here?

```r
new_lm <- function(x,..., class = character()) {
  stopifnot(is.list(x))

  stopifnot(has_name(x, “coefficients”))
  stopifnot(is.double(x[[“coefficients”]]))
  
  structure(
    x,
    ...,
    class = c(class, “lm”)
  )
}
```

If you extend `lm`, it would be your job to ensure that any new list elements you add to `x` exist in `new_extended_lm()`, but you would let `new_lm()` do the checks on the preexisting elements.

**Comment by hadley** [comment]
I think `new_lm()` should have an argument for each field, and it should validate its type.

**Comment by DavisVaughan** [comment]
Gotcha. I see `vctrs:::new_sclr()` now. I guess the loss of being able to set other attributes isn't a big deal here.

``` r
new_model_lm <- function(coef, resid, ..., class = character()) {
  stopifnot(is.double(coef))
  stopifnot(is.double(resid))
  
  fields <- list(
    coef = coef, 
    resid = resid, 
    ...
  )
  
  structure(
    fields,
    class = c(class, "model_lm")
  )
}

new_extended_lm <- function(extension, coef, resid, ..., class = character()) {
  stopifnot(is.double(extension))
  
  new_model_lm(
    coef = coef, 
    resid = resid, 
    extension = extension, 
    class = c(class, "extended_lm")
  )
}
  
str(new_model_lm(1, 2))
#> List of 2
#>  $ coef : num 1
#>  $ resid: num 2
#>  - attr(*, "class")= chr "model_lm"

str(new_extended_lm(1, 1, 1))
#> List of 3
#>  $ coef     : num 1
#>  $ resid    : num 1
#>  $ extension: num 1
#>  - attr(*, "class")= chr [1:2] "extended_lm" "model_lm"
```

**Comment by hadley** [comment]
Yeah, I'd probably go so far as to say that you shouldn't use attributes for scalar classes.
