### ISSUE TITLE
Trying to create an offline copy with render_site

### ISSUE THREAD

**Issue by GreyMerchant** [hadley/adv-r#1580]
Hello, 

I am looking to create an offline searchable copy of the book for myself because I am often in the situation where I might not have internet and the inconvenience of a book with a laptop just doesn't work within the space that I have.

I have tried the following bit of code and it seems to compile.

```
library(here)
library(rmarkdown)

rmarkdown::render_site(input = here(),
                       output_format = 'bookdown::pdf_book', 
                       encoding = 'UTF-8')
```

I have fixed a couple of package missing so I have been making progress but I am currently stuck here with this specific error:

```
Quitting from lines 788-794 (Conditions.Rmd) 
Error: `err` inherits from `deprecatedWarning/warning/condition` not `error_bad_argument`.

Execution halted
Error in Rscript_render(f, render_args, render_meta) : 
  Failed to compile Conditions.Rmd
```
Any idea of what to do?

**Comment by hadley** [comment]
I can't reproduce this, either locally or on [travis](https://travis-ci.org/hadley/adv-r).

**Comment by GreyMerchant** [comment]
Seems that this was due to older versions of packages specifically versions earlier than 0.4.2 for rlang
