### ISSUE TITLE
Installing "lineproof" from github fails on MacOS Catalina

### ISSUE THREAD

**Issue by Shellback3** [hadley/adv-r#1584]
RStudio, MacOS Cataline, macBook Pro
In the Memory Section
Here's the error:

    > devtools::install_github("hadley/lineprof")

    Downloading GitHub repo hadley/lineprof@master
    Error: Failed to install 'lineprof' from GitHub:
    Could not find tools necessary to compile a package
    Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

Attempting to diagnose the problem fails also, a pop-up refers me to an old cNet article with a solution that appears to be out of date.  FWIW MacOS informs me that they are now using zsh.

**Comment by hadley** [comment]
I'd recommend switching to the second edition: https://adv-r.hadley.nz/perf-measure.html

**Comment by Shellback3** [comment]
Thanks for the really quick response! I shall do so ...
