### ISSUE TITLE
Question about examples in 6.5.3

### ISSUE THREAD

**Issue by svkucheryavski** [hadley/adv-r#1595]
Thanks once again for the great book. I have a question about examples you have shown in the section 6.5.3. For example this code:

```
sample <- function(x, size = NULL, replace = FALSE, prob = NULL) {
  if (is.null(size)) {
    size <- length(x)
  }
  
  x[sample.int(length(x), size, replace = replace, prob = prob)]
}
```

Isn't it better to write as:

```
sample <- function(x, size = length(x), replace = FALSE, prob = NULL) {
  x[sample.int(length(x), size, replace = replace, prob = prob)]
}
```

As in this case we will not refer to variables defined inside the function and the arguments should be clear enough for user.

Also related to the infix function you showing later:

```
`%||%` <- function(lhs, rhs) {
  if (!is.null(lhs)) {
    lhs
  } else {
    rhs
  }
}
```

Which can be written as

```
`%||%` <- function(lhs, rhs) {
  if (!is.null(lhs)) return(lhs)
  rhs
}
```

It would be great if you share your opinion on these examples, if you have time and wish of course.

**Comment by hadley** [comment]
I don't remember the exact point I was trying to make in 6.5.3, but I agree your version is a little better.

I don't love your rewrite of `%||%` because to me it looks less symmetrical, so it's harder to see what the intent is.
