### ISSUE TITLE
Example In Lazy Evaluation Functions Section does not work

### ISSUE THREAD

**Issue by jam1015** [hadley/adv-r#1609]
You claim that this code
```
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
adders[[1]](10)
#> [1] 11
adders[[10]](10)
```
creates functions that add 10 no matter what, but the functions clearly work.

You say the output will be different than this code:
```
add <- function(x) {
  force(x)
  function(y) x + y
}
adders2 <- lapply(1:10, add)
adders2[[1]](10)
#> [1] 11
adders2[[10]](10)
```

maybe there is something that I am missing.

**Comment by hadley** [comment]
You're probably reading the 1st edition; R's behaviour changed since that was published. Try the 2e instead: http://adv-r.hadley.nz/
