### ISSUE TITLE
Reference importance of NA types

### ISSUE THREAD

**Issue by dkahle** [hadley/adv-r#1635]
In the section on [missing values in the vectors chapter](https://github.com/hadley/adv-r/blob/master/Vectors.Rmd#L182), the distinction of types of missingness (e.g. `NA_character_`) is downplayed as somewhat of an inconsequential oddity, but since __dplyr__'s rebasing on __vctrs__ this seems like a much bigger deal. You may want to consider referencing how this can make a difference __vctrs__-based implementations like those you see in __dplyr__.

Example:

```r
library("tidyverse")

is.even <- function(x) x %% 2 == 0

tibble("x" = 1:4) %>% 
  mutate(x = if_else(is.even(x), x, NA))
#> Error: Problem with `mutate()` input `x`.
#> x `false` must be an integer vector, not a logical vector.
#> ℹ Input `x` is `if_else(is.even(x), x, NA)`.
```
That's a pretty cryptic message if you're not familiar with the types. By contrast, if you are, replacing `NA` with `NA_integer_` works as intended:
```r
tibble("x" = 1:4) %>% 
  mutate(x = if_else(is.even(x), x, NA_integer_))
#> # A tibble: 4 x 1
#>       x
#>   <int>
#> 1    NA
#> 2     2
#> 3    NA
#> 4     4
```

**Comment by hadley** [comment]
The problem is that here dplyr _doesn't_ use vctrs — if it did, you wouldn't see this error. (And the plan is to use vctrs in `if_else()` so that this issue goes away).
