### ISSUE TITLE
Environments section: Layout bug on small screen

### ISSUE THREAD

**Issue by dirkschumacher** [hadley/adv-r#508]
See attached screenshot. You cannot fully read the content.
Firefox Android 4.2 (also happens on the desktop firefox)
![2014-05-27 11 46 18](https://cloud.githubusercontent.com/assets/1569647/3090967/b964f744-e594-11e3-87fb-d79370bbf559.png)

**Comment by hadley** [comment]
Will be moving to bookdown in the near future
