### ISSUE TITLE
Wrong/misleading information in Environments (multiple names pointing to the same object)

### ISSUE THREAD

**Issue by daattali** [hadley/adv-r#640]
Under "[Environment Basics](http://adv-r.had.co.nz/Environments.html#env-basics)", it says "multiple names can point to the same object." followed by a diagram that shows two names pointing to the same object.   
![](http://adv-r.had.co.nz/diagrams/environments.png/multiple-names.png)  

The diagram shows `a` and `d` both pointing to the same object. But this suggests that they are both actually using the same object in memory.  This can be disproved with either `pryr::address(e$a) == pryr::address(e$d)` (returning FALSE) or by doing `e$a[1] <- 100; e$d;` and seeing that the vector hasn't changed in `d`.

Maybe I'm just misinterpreting the diagram.

**Comment by hadley** [comment]
I don't think address works recursive?
, and modifying one creates a copy. They're definitely pointing to the same object
