### ISSUE TITLE
Performance chapter: profiling times in the text do not agree with reported times from code

### ISSUE THREAD

**Issue by daattali** [hadley/adv-r#646]
When reading through the [performance](http://adv-r.had.co.nz/Performance.html) chapter, many times after running a `microbenchmark()` there is a piece of text describing the result.  The numbers in the text are usually very different from what the code shows, which caused me some confusion initially. 

For example, after this piece of code

```
x <- runif(100)
microbenchmark(
  sqrt(x),
  x ^ 0.5
)
#> Unit: nanoseconds
#>     expr    min     lq  mean median     uq    max neval
#>  sqrt(x)  1,570  1,830  2554  2,050  2,310 31,400   100
#>    x^0.5 15,200 15,500 16769 15,600 16,000 71,200   100
```

It says that each computation takes about 800 ns, but I could not figure out where you got that number from (I'm assuming in a previous compilation of the book, the median was 800?).

This happens several more times later.  I think trying to use inline R while still keeping the numbers readable is overkill, but it might be a good idea to just add a short note somewhere saying that the numbers in the text do not necessarily match the numbers in the output, so that readers will not go crazy trying to figure out where you're getting the numbers from.

**Comment by daattali** [comment]
Related: I'd argue that in the printed version of the book, since it's much more stable and only gets printed once, it would be worth to make the numbers match

**Comment by hadley** [comment]
The printed version of the book (run on my computer) is different to the website (run on travis). I would've thought the printed version would be ok

**Comment by daattali** [comment]
I haven't seen the printed version, so maybe that's true. But regardless,
I'd still prefer to have such a note in the text to not get confused
