### ISSUE TITLE
Add search functionality for the book (using Google Custom Search Engine?)

### ISSUE THREAD

**Issue by daattali** [hadley/adv-r#668]
There have been several times when I was trying to remember something that I learned from the book, and I could only remember a keyword.  What I do is I go to the book homepage and open all the chapters in different tabs and then "Find on page" until I find what I was looking for.

It would be nice IMO to maybe add search to the site. Google makes it very easy to add a Google Search to your site.

**Comment by hadley** [comment]
Will be switching to bookdown soon
