### ISSUE TITLE
list modification in place copies

### ISSUE THREAD

**Issue by nicolasCoutin** [hadley/adv-r#681]
Compared to the [modification-in-place](http://adv-r.had.co.nz/memory.html#modification) section:

you can't modify a list in place according to outlined?

### Cannot reproduce your example results w/ `pryr 0.1`
```r
library(pryr)
x <- data.frame(matrix(runif(100 * 1e4), ncol = 100))
medians <- vapply(x, median, numeric(1))
for(i in 1:5) {
  x[, i] <- x[, i] - medians[i]
  print(c(address(x), refs(x)))
}
#> [1] "0x102a2baa0" "2"          
#> [1] "0x101686fb0" "2"          
#> [1] "0x10168fe10" "2"          
#> [1] "0x101669f90" "2"          
#> [1] "0x10166e700" "2" 
y <- as.list(x)
for(i in 1:5) {
  y[[i]] <- y[[i]] - medians[i]
  print(c(address(y), refs(y)))
}
#> [1] "0x10166bc20" "2"          
#> [1] "0x10166add0" "2"          
#> [1] "0x101681300" "2"          
#> [1] "0x101621480" "2"          
#> [1] "0x10165b2b0" "2"
```
### session
```r
sessionInfo()
#> R version 3.2.0 (2015-04-16)
#> Platform: x86_64-apple-darwin13.4.0 (64-bit)
#> Running under: OS X 10.10.3 (Yosemite)
#> 
#> locale:
#>   [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#>   [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>   [1] pryr_0.1
#> 
#> loaded via a namespace (and not attached):
#>   [1] magrittr_1.5       tools_3.2.0        Rcpp_0.11.6        stringi_0.5-1      codetools_0.2-11  
#> [6] stringr_1.0.0.9000
```

## if I update to `pryr 0.1.0.9000` I now get:
```r
library(pryr)
x <- data.frame(matrix(runif(100 * 1e4), ncol = 100))
medians <- vapply(x, median, numeric(1))
for(i in 1:5) {
  x[, i] <- x[, i] - medians[i]
  print(c(address(x), refs(x)))
}
#> [1] "0x1016d3ba0" "2"          
#> [1] "0x10167bdb0" "2"          
#> [1] "0x101692ff0" "2"          
#> [1] "0x1016cd790" "2"          
#> [1] "0x10165c090" "2"
y <- as.list(x)
for(i in 1:5) {
  y[[i]] <- y[[i]] - medians[i]
  print(c(address(y), refs(y)))
}
#> [1] "0x1016c6f00" "1"          
#> [1] "0x1016c6f00" "1"          
#> [1] "0x1016c6f00" "1"          
#> [1] "0x1016c6f00" "1"          
#> [1] "0x1016c6f00" "1" 


sessionInfo()
#> R version 3.2.0 (2015-04-16)
#> Platform: x86_64-apple-darwin13.4.0 (64-bit)
#> Running under: OS X 10.10.3 (Yosemite)
#> 
#> locale:
#>   [1] en_CA.UTF-8/en_CA.UTF-8/en_CA.UTF-8/C/en_CA.UTF-8/en_CA.UTF-8
#> 
#> attached base packages:
#>   [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> other attached packages:
#>   [1] pryr_0.1.0.9000
#> 
#> loaded via a namespace (and not attached):
#>   [1] magrittr_1.5       tools_3.2.0        Rcpp_0.11.6        stringi_0.5-1      codetools_0.2-11  
#> [6] stringr_1.0.0.9000
```

### So what's what here? I'm a whittle confused...

This actually reflects an ever-present R quandary of mine. It's actually quite difficult (for me anyway) to figure out what best practice is for any arbitrary task. (Now I should be clear I am a huge fan of the greatness that all of rstats and rstudio are what each stands for). But it would be sweet if there was a place I could go and it would tell me 'these represent best practice standards for modifying a list as of May 2015)... or whatnot. I'm not sure if that's even a good/feasible idea. [CppSamples](http://www.cppsamples.com/) is something which I think tries that (but IMHO is not so successful).

**Comment by hadley** [comment]
I don't quite get your question? The result seems correct with the updated pryr

**Comment by nicolasCoutin** [comment]
- I was (unclearly) asking which is actually happening. If I'm safe to assume the updated pryr gets it right then all is well and this may be closed (although perhaps this should be noted in the book).
- The remaining dribble is to highlight that I think that should there be time to set it up a "best practices" for any given R task would be wonderful (which would prioritize clarity & performance).

**Comment by hadley** [comment]
There was a bug in pryr where `address()` accidentally took a reference - that caused the buggy behaviour.

Best practice for R, is not to worry about copies until you discover a performance problem. Then benchmark and look for the work offenders.
