### ISSUE TITLE
"8.1 Environment basics" doubt

### ISSUE THREAD

**Issue by lbraglia** [hadley/adv-r#687]
Hi Hadley, 

don't know if this is the right place, but following the first lines from 8.1

```
e <- new.env()
e$a <- FALSE
e$b <- "a"
e$c <- 2.3
e$d <- 1:3
```

The objects don’t live in the environment so multiple names can point to the same object. But why?

```
e$a <- e$d
e$a[1] <- 0
e$a
e$d
```
Can't be environments elements thought as pointers?

Thanks, Luca

**Comment by hadley** [comment]
The objects live in memory somewhere, and then an environment points to them. But rather than thinking of pointers, I think it's better to think about an environment associating a name with an object

**Comment by lbraglia** [comment]
ok, thanks, but it's not clear to me why `e$a` and `e$d` are different (after `e$a[1] <- 0`) in the previous example . 
Given the graph (2nd at page 125 of the book), I expected they was associated with the same memory location therefore being equal...

thanks, Luca

**Comment by hadley** [comment]
Pointing to the same place in memory is just a performance optimisation. You should think about the two vectors as being unrelated - when you modify one, R makes a copy so as not to interfere with the other.

**Comment by lbraglia** [comment]
ah ok, thanks
