### ISSUE TITLE
Add .Renviron to Environment's chapter

### ISSUE THREAD

**Issue by dlebauer** [hadley/adv-r#693]
I gather @hadley wrote this gem in the httr API best practices vignette:

> FAQ: Why define this environment variable via .Renviron instead of in .bash_profile or .bashrc?
> 
> Because there are many combinations of OS and ways of running R where the .Renviron approach “just works” and the bash stuff does not. When R is a child process of, say, Emacs or RStudio, you can't always count on environment variables being passed to R. Put them in an R-specific start-up file and save yourself some grief.

I think this would be a useful addition to the Environments Chapter, and might have kept me out of a few Emacs quagmires such as http://stackoverflow.com/q/11005478/199217 and http://stackoverflow.com/q/19126370/199217

**Comment by hadley** [comment]
That gem is actually from @jennybc, and in the not to distant future we'll have an even better approach that avoids .Renviron altogether (in favour of using the OS keychain)
