### ISSUE TITLE
Better subscramble explanation

### ISSUE THREAD

**Issue by hadley** [hadley/adv-r#694]
``` R
subscramble <- function(x, cond1) {
  scramble(subset2(x, cond1))
}

scramble <- function(x) x[sample(nrow(x)), ]

subset2 <- function(x, cond2) {
  cond3 <- substitute(cond2)
  r <- eval(cond3, x, parent.frame())
  x[r, ]
}

subscramble(mtcars, cyl == 4)
#  Error in eval(expr, envir, enclos) : object 'cyl' not found
traceback()
#5: eval(expr, envir, enclos)
#4: eval(cond3, x, parent.frame()) at #3
#3: subset2(x, cond1) at #1
#2: scramble(subset2(x, cond1)) at #2
#1: subscramble(mtcars, cyl == 4)
```

So:
1. `cond3` is `quote(cond1)`
2. `eval(quote(cond1), x, parent.frame())` doesn't find `cond1` in the data frame, so it looks in the `parent.frame()`
3. In the `parent.frame()`, `cond1` is `cyl == 4`, but cyl isn't defined, so it errors.

**Comment by samuel-liyi** [comment]
I came from the booksite to this by googling, this example is much more clearer than the one in the book !

**Comment by hadley** [comment]
Closing since the book now takes a different approach
