### ISSUE TITLE
Computing on the Language: Question 4.4

### ISSUE THREAD

**Issue by michaelquinn32** [hadley/adv-r#697]
Hi,

I'm working through the book, and I'm not sure about the intent of this question. I believe that the function in `plyr` is missing. Maybe it's a typo? Is `plyr`'s `quote` function actually the intended reference?

> What’s the escape hatch for `ggplot2::aes()`? What about `plyr::()`? What do they have in common? What are the advantages and disadvantages of their differences?

**Comment by jennybc** [comment]
I have the same question. The exercise appears at end of [Calling from another function](http://adv-r.had.co.nz/Computing-on-the-language.html#calling-from-another-function) section.

**Comment by jennybc** [comment]
Before bf4f81f8cac27ae1ab11eb04bf23e6a130dd347c, this used to read `plyr::.` which actually makes sense FWIW.

**Comment by hadley** [comment]
Yeah, should definitely refer to `aes()` and `.()`
