### ISSUE TITLE
Functional Operators: Question 3.4

### ISSUE THREAD

**Issue by michaelquinn32** [hadley/adv-r#698]
Hi,

I'm working through the questions in the book. I'm struggling with question 4 in the input FO's section of the chapter on functional operators.

> You’ve seen five functions that modify a function to change its output from one form to another. What are they? Draw a table of the various combinations of types of outputs: what should go in the rows and what should go in the columns? What function operators might you want to write to fill in the missing cells? Come up with example use cases.

I'm confused by a couple of issues.
1. The location of the question is a little weird. Are we referring to functions in the input FO's section or in the previous output FO's section?
2. Does the word "form" in the question refer to changes in data type, which is what we do with the functions `as.data.frame.function` and `as.matrix.function` that were created in the previous problem? Or are we talking about something simpler, like `Negate`? With these and `as.list.function`, I can still only think up four. My intuition says that this is something similar to the variety of `ply` functions in `plyr`, but nothing talked about this package in the last two sections.

**Comment by hadley** [comment]
This section has been removed altogether in 2nd edition.
