### ISSUE TITLE
Bad partial() examples

### ISSUE THREAD

**Issue by Deleetdk** [hadley/adv-r#713]
http://adv-r.had.co.nz/Function-operators.html#input-fos

```
> sum = partial(sum, na.rm = TRUE)
> sum(1, 2, 3)
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
> sum(c(1, 2, 3))
Error: evaluation nested too deeply: infinite recursion / options(expressions=)?
Error during wrapup: evaluation nested too deeply: infinite recursion / options(expressions=)?
```

The problem disappears if one avoids using the same names as the primitive functions:

```
> sum2 = partial(sum, na.rm = TRUE)
> sum2(1, 2, 3)
[1] 6
> sum2(c(1, 2, 3))
[1] 6
```

It seems that partial() creates an infinite loop for calling `sum` when it is named "sum", calling itself over and over instead of calling the primitive function. So, it is fixable too by defining the partial with explicit reference to the primitive function:

```
> sum = partial(.Primitive("sum"), na.rm = TRUE)
> sum(1, 2, 3)
[1] 6
> sum(c(1, 2, 3))
[1] 6
```

**Comment by Deleetdk** [comment]
I note that in his examples, he created the functions inside a list. I forgot to do so when I ran the code (only copied part of it), which is why I got the problem.

**Comment by hadley** [comment]
Yes, because you're creating a new function called sum that will override the existing one. Just be more explicit: `pryr::partial(base::sum, na.rm = TRUE)`
