### ISSUE TITLE
A note about Vectorize()

### ISSUE THREAD

**Issue by Deleetdk** [hadley/adv-r#714]
It isn't mentioned in the book, but Vectorize has an important limitation worth noting, namely that it doesn't work with primitive functions. This is because it requires a formals() and primitives lack that. E.g.

```
> rep2 = Vectorize(rep, "digits")
Error in Vectorize(rep, "digits") : 
  must specify names of formal arguments for 'vectorize'
```

Which is a somewhat cryptic error. I found the answer [here](http://stackoverflow.com/questions/31658451/how-to-vectorize).

**Comment by hadley** [comment]
Yeah, that's documented. I only mention it briefly and I don't think it's necessary to go into all the deatils.
