### ISSUE TITLE
Idea: forkable style guide?

### ISSUE THREAD

**Issue by kenahoo** [hadley/adv-r#765]
The style guide you provide in the book is good, thanks for writing it.

It would be cool if we could tweak it or add to it in our own organization's fork of it, making it somehow clear which parts are from your original source and which parts are our own local dialect.  And as a fork rather than a copy, we could integrate any changes/fixes that get made in the root later.

Is that something you've seen done elsewhere in a style guide?

**Comment by hadley** [comment]
I have not. It seems like a good idea, but out of scope for advanced-R currently.  (Although maybe I should pull out the style guide into a separate repo).

**Comment by hadley** [comment]
Now at https://github.com/tidyverse/style 😄

**Comment by kenahoo** [comment]
Excellent!  Thanks!
