### ISSUE TITLE
noNA in Rcpp.

### ISSUE THREAD

**Issue by rorynolan** [hadley/adv-r#776]
For me it wasn't clear for me what noNA does. I thought it would work like !anyNA() but in fact noNA returns a vector if given a vector (as far as I can tell), but I still can't tell what it's doing. Maybe others would appreciate more clarity on this, or maybe I'm the only one!
Love your work, really helping me in my research on HIV.
Thanks!

**Comment by hadley** [comment]
Does this help? 

Finally, `noNA(x)` asserts that the vector `x` does not contain any missing values, and allows optimisation of some mathematical operations. For example, when computing the mean of a vector with no missing values, Rcpp doesn't need to check each value is not missing when computing the sum and the length.

**Comment by rorynolan** [comment]
Firstly, thanks, it clears it up massively. Secondly, I'd like to (tentatively) correct my question. As far as I can tell now, `noNA` from Rcpp does indeed behave like `!anyNA` in R.
Thanks again Hadley, great that you care to reply to stuff like this.

**Comment by rorynolan** [comment]
Just for other people who struggled with this, here's the question I asked on StackOverflow, with a really nice answer. Dirk Eddelbuettel even chimed in with a comment (I'm honoured).
http://stackoverflow.com/questions/41873067/how-is-nona-used-in-rcpp
