### ISSUE TITLE
S3 constructors for existing classes

### ISSUE THREAD

**Issue by jimvine** [hadley/adv-r#797]
I like the use of constructors for existing classes (new_Date and new_POSIXct in the current draft) to demonstrate the concept. A useful addition would be to say whether you think this is a good idea or not. I.e., is it **just** for demo purposes, or something you'd be likely to do in practice? Something like either:

"This is helpful for demonstrating the concept of constructors, but not something you should normally do for existing classes, because..."

Or:

"If you think that your functions are likely to be creating a lot of objects of an existing class, it may actually be a good idea to create the missing constructor."

(Not sure whether it's needed for little sentence suggestions like this, but just in case: I assign the copyright of this contribution to Hadley Wickham.)

**Comment by hadley** [comment]
Good point, I'll add a note
