### ISSUE TITLE
Contribute/build tools

### ISSUE THREAD

**Issue by setempler** [hadley/adv-r#799]
As far as I understand from the code, building the book can be performed by running the `book/build-book.r` script. Maybe I didn't get all RStudio features yet, and it is possible to build the book by a keybinding. Thus, are there any attempts to 

* at least include a short note (e.g. into `README.md`) on that, so contributors can find and apply the build tool?
* use a `Makefile` to perform the build? If interested, see [this small example](https://github.com/setempler/miscset/blob/master/Makefile#L14-L21) on how to handle more complex R code in a `Makefile`.

Thanks

**Comment by hadley** [comment]
To build the book, you run `bookdown::build_site()`. For local prototyping, you just need to re-knit the individual chapters. The stuff in `book/` is a remnant of the previous process that I'll replace once I send the book back to the publishers.

**Comment by setempler** [comment]
thanks
