### ISSUE TITLE
Anonymous Functions Excercise 1

### ISSUE THREAD

**Issue by jrnold** [hadley/adv-r#800]
In Excercise 1 of [Anonymous Functions](http://adv-r.had.co.nz/Functional-programming.html#anonymous-functions), the question asks:

> Given a function, like "mean", `match.fun()` lets you find a function. Given a function, can you find its name? Why doesn’t that make sense in R?

I know what it's getting at, that a "name" maps to a value, but values aren't uniquely associated with names. However, in the same way `match.fun` recurses over environments to find a name (which is unique in an environment, but not all environments), a function could recuse over over environments to find the name (or names) that have a given value.

```r
match_value <- function(value, env = parent.frame()) {
  if (identical(env, emptyenv())) {
    # Base case
    stop("Can't find an object", call. = FALSE)
  } else {
    for (name in ls(envir = env, all.names = TRUE)) {
      if (identical(env[[name]], value)) {
        return(list(envir = env, name = name))
      }
    }
    # Recursive case
    find_by_value(value, parent.env(env))
  }
}
find_by_value(sum)
find_by_value(print)
```
The code could of course be adapted to find multiple names matching functions.

I assign the copyright of this contribution to Hadley Wickham

**Comment by hadley** [comment]
The problem is that you can only find the parents of an environment, not its children, so this is necessarily only going to be a partial search.
