### ISSUE TITLE
Incorrect statement about midpoint numerical integration of pi

### ISSUE THREAD

**Issue by jrnold** [hadley/adv-r#801]
In the section [Case study: numerical integration](http://adv-r.had.co.nz/Functional-programming.html#numerical-integration) the example with midpoint and trapezoid states "Neither of these functions gives a very good approximation". But in the example provided, the midpoint produces almost precisely `pi`:
```{r}
midpoint <- function(f, a, b) {
  (b - a) * f((a + b) / 2)
}

midpoint(sin, 0, pi)
base::pi
```
```
[1] 3.141593
[1] 3.141593
```
 

"I assign the copyright of this contribution to Hadley Wickham"

**Comment by hadley** [comment]
But the value of the integral should be 2 - I'll see if I can make this easier to see in the text.
