### ISSUE TITLE
Edit buttons no longer work

### ISSUE THREAD

**Issue by jrnold** [hadley/adv-r#802]
On the webpage, the edit buttons give 404 errors. It looks like an issue with the casing of the R markdown extension. They are linking to `*.rmd` instead of `*.Rmd`. E.g. https://github.com/hadley/adv-r/edit/master/index.rmd does not work, but https://github.com/hadley/adv-r/edit/master/index.Rmd does.

**Comment by hadley** [comment]
Duplicate of #798
