### ISSUE TITLE
Incorrect example in "Lazy Evaluation"

### ISSUE THREAD

**Issue by timgoodman** [hadley/adv-r#810]
In [this section](http://adv-r.had.co.nz/Functions.html#lazy-evaluation) it is suggested that:
```
add <- function(x) {
  function(y) x + y
}
adders <- lapply(1:10, add)
adders[[1]](10)
adders[[10]](10)
```
gives a result which was probably not intended, and that 
```
add <- function(x) {
  force(x)
  function(y) x + y
}
adders2 <- lapply(1:10, add)
adders2[[1]](10)
adders2[[10]](10)
```
fixes the problem.  But in fact, they both give the same output. 

Perhaps something like this was intended:
```
add <- function(x) {
  function(y) x + y
}
adders = list()
for (x in 1:10) adders[[x]] <- add(x)
adders[[1]](10)
adders[[10]](10)
```
(Here the _actual_ argument `x` is reused each time, whereas in the previous examples `x` is only the _formal_ argument.)

**Comment by yutannihilation** [comment]
This seems to have been pointed out many times and is recognized very well by the author;) See #803.

**Comment by timgoodman** [comment]
@yutannihilation OK, thanks.  I checked the list of open issues before creating this, but didn't think to check the closed ones. :)

Closing this.
