### ISSUE TITLE
Figures don't match text in "Environment basics"

### ISSUE THREAD

**Issue by timgoodman** [hadley/adv-r#811]
In [this section](http://adv-r.had.co.nz/Environments.html#env-basics), the text shows the value of `e$b` being updated (`e$b <- e$d` and then `e$b <- 1:3`) but the corresponding images show the value of `e$a` being updated.

**Comment by stephens999** [comment]
I think this relates to PR #796

**Comment by jennybc** [comment]
Yeah, it's now also part of #853 as well.

**Comment by hadley** [comment]
Duplicate of #853
