### ISSUE TITLE
Edit this page link points to non-existent .rmd instead of .Rmd source (and it matters)

### ISSUE THREAD

**Issue by dlebauer** [hadley/adv-r#813]
The 'Edit This Page' button on the memory page http://adv-r.had.co.nz/memory.html points to [https://github.com/hadley/adv-r/edit/master/memory.**r**md](https://github.com/hadley/adv-r/edit/master/memory.rmd) which returns the GitHub 404 page but it should really be pointing to  [https://github.com/hadley/adv-r/edit/master/memory.**R**md](https://github.com/hadley/adv-r/edit/master/memory.Rmd)

**Comment by dlebauer** [comment]
Also occurs for 100% of a random sample of 3 additional pages

**Comment by fangly** [comment]
I observed  this also for the contribute and environments chapters.

**Comment by hadley** [comment]
Duplicate of #798
