### ISSUE TITLE
lookup package

### ISSUE THREAD

**Issue by jennybc** [hadley/adv-r#815]
It would be great to feature @jimhester's [lookup package](https://github.com/jimhester/lookup#readme) heavily here. I dip in and out of this book randomly, but I don't recall there being anything that rivals lookup for helping people find and read the R source.

**Comment by jimhester** [comment]
I guess one issue is that **lookup** is not on CRAN and has dependencies (mainly [highlite](https://github.com/jimhester/highlite) and [gh](https://github.com/r-pkgs/gh)) that are not on CRAN. 

Getting **highlite** on CRAN will take some work as it needs to compile LUA, then compile an external highlight library, so making sure it works cross platform will take some time. On the other hand no one has yet complained about it not working on windows, so maybe it just works already and will be easy?🤞

 **gh** I don't think will be too hard.

**Comment by hadley** [comment]
Could you switch to some other existing syntax highlighting tool?  Another option would be to make this an html widget, which might make highlighting easier.

**Comment by jimhester** [comment]
It needs C and R highlighting, but yeah I could probably use something else. Also at least when using **lookup** in RStudio you don't need **highlite** at all, as it uses the IDEs native syntax highlighting, **highlite** is only used in terminal R / ESS etc.

Looking at the repo I guess highlite does work on Windows (at least on Appveyor), so it could go to CRAN without too much work, although it will probably fail on Solaris...

**Comment by hadley** [comment]
I'm going to close this for now. If highlight makes it to CRAN before the book is published, I'll use it, but I don't think using lookup in the book is important enough that it should force Jim to spend time getting it to CRAN.

**Comment by jennybc** [comment]
lookup (the package and the lifestyle) is something we can continue to advocate for in other, more fluid venues, like the "What They Forgot" workshop / bookdown site.
