### ISSUE TITLE
First lazy evaluation example is unclear

### ISSUE THREAD

**Issue by arthur-st** [hadley/adv-r#837]
![image](https://user-images.githubusercontent.com/29796606/28269999-9bea83ae-6b0c-11e7-9ee3-04875eb24607.png)

This example does not convey the lazy evaluation, e.g. what a reader will attempt is following:

```r
> add <- function(x) {
+     function(y) x + y
+ }
> adders <- lapply(1:10, add)
> adders[[1]](10)
[1] 11
> adders[[10]](10)
[1] 20
> adders[[1]](1)
[1] 2
> adders[[10]](1)
[1] 11
```
Which in no way differs from the example meant to alleviate the issue:
```r
> add <- function(x) {
+     force(x)
+     function(y) x + y
+ }
> adders2 <- lapply(1:10, add)
> adders2[[1]](10)
[1] 11
> adders2[[10]](10)
[1] 20
> adders2[[1]](1)
[1] 2
> adders2[[10]](1)
[1] 11
```

I assign the copyright of this contribution to Hadley Wickham.

**Comment by david-jankoski** [comment]
I've seen this come up as an recurring issue since some time - i think the answer lies in the 
[news release of R 3.2.0](https://stat.ethz.ch/pipermail/r-announce/2015/000583.html), behaviour of lapply has been changed to the opposite of what the book illustrates.  

>  * Higher order functions such as the apply functions and Reduce()
     now force arguments to the functions they apply in order to
     eliminate undesirable interactions between lazy evaluation and
     variable capture in closures.  This resolves PR#16093.

I think the book is undergoing an update.

**Comment by psychelzh** [comment]
@david-jankoski Thank you for your explanation. I was spending a lot of time trying to understand the difference between these two examples, but in vain. Now I know there is a new release that changed the behavior of `lapply`.

**Comment by david-jankoski** [comment]
no worries - it confused me and a lot of other people too. i guess this case of a "catch" in lazy evaluation does not apply anymore so not sure what's going to happen to the example in the book. maybe leave it in as a reminder that this can happen - or find a place where this still applies...

**Comment by bborgesr** [comment]
@hadley, just ran into this when preparing an article on a related topic for Shiny. Given I'm in this headspace, if you want, I can try my hand at a PR to update this particular section of the book with another example that _does_ illustrate lazy evaluation in the current R version.

**Comment by hadley** [comment]
@bborgesr sure, that'd be great!
