### ISSUE TITLE
Orders of "on.exit" in Example Code

### ISSUE THREAD

**Issue by feimingchen** [hadley/adv-r#841]
In Chapter "Function", Section "Return values",  Exercise 4 Example code of "on.exit".  

Line   
       `on.exit(sink(), add = TRUE)`
should precede Line: 
       `on.exit(file.remove(temp), add = TRUE)`

Since we are supposed to close the sink file before removing it.  Right?

**Comment by hadley** [comment]
I had assumed that `on.exit()` was last-in first-out

```R
f <- function() {
  on.exit(message("a"), add = TRUE)
  on.exit(message("b"), add = TRUE)
}
f()
#> a
#> b
```

But it's not, so I'll need to rethink this approach
