### ISSUE TITLE
Under Enviroment Basics, figures don't match code.

### ISSUE THREAD

**Issue by btbroderick** [hadley/adv-r#863]
[http://adv-r.had.co.nz/Environments.html](url)
```
e$b <- e$d
e$b <- 1:3
```
The figures corresponding to these two lines of code in the attached link don't seem to match up.

**Comment by geneorama** [comment]
I think the diagram was rotated at some point and the examples got out of whack.

Currently it's like this:
```
---------
| b | a |
|---|---|
| c | d |
---------
```
But deep down I think that it *wants* to be this:
```
---------
| a | b |
|---|---|
| c | d |
---------
```

**Comment by jennybc** [comment]
I think this has been straightened out in the still-developing 2nd edition:

http://adv-r.hadley.nz/environments.html#env-basics
