### ISSUE TITLE
S3/[.class subtleties

### ISSUE THREAD

**Issue by tjmahr** [hadley/adv-r#870]
I think the S3 chapter would benefit with at least one example of writing a method for a low-level function like `[`. I ran into a confusing problem with writing my own S3 vector class where `sort()` would unclass it. 

How it might help the text:

1. Advise the reader that when they write an S3 vector class, they have to implement some basic vector methods. (Thus, a scalar class is probably easier.) 
2. The text only demonstrates built-in R classes so it hides some of these subtleties. If the factor example had a different class like `factor2`, it would be more fragile. It's more useful if these issues are mentioned.
3. Demonstrate an infix function definition.

## Context

I wrote an S3 class following the suggestions in the book for our [stan-dev/bayesplot](https://github.com/stan-dev/bayesplot) package. The class is a vector class for diagnostic stats, and we validate them and dispatch on them so an S3 class seems like a good fit. We want to use named vectors so that we can carry along parameter names with the diagnostic stats if possible. I come up with:

```r
new_rhat <- function(x) {
  # Convert a 1-d arrays to a vectors
  if (is.array(x) && length(dim(x)) == 1) {
    x <- as.vector(x)
  }
  validate_rhat(to_rhat(x))
}

validate_rhat <- function(x) {
  stopifnot(is.numeric(x), !is.list(x), !is.array(x))
  if (any(x < 0, na.rm = TRUE)) {
    stop("All 'rhat' values must be positive.", call. = FALSE)
  }
  x
}

to_rhat <- function(x) {
  structure(x, class = c("rhat", "numeric"), names = names(x))
}

hats <- new_rhat(c("(Intercept)" = 1.0, "beta[1]" = 1.1, "alpha" = 1.02))
hats
#> (Intercept)     beta[1]       alpha 
#>        1.00        1.10        1.02 
#> attr(,"class")
#> [1] "rhat"    "numeric"
```

But I found that it gets unclassed very easily.

```r
# Class gets lost
hats[-1]
#> beta[1]   alpha 
#>    1.10    1.02
sort(hats)
#> (Intercept)       alpha     beta[1] 
#>        1.00        1.02        1.10
rev(hats)
#>       alpha     beta[1] (Intercept) 
#>        1.02        1.10        1.00
```

So I had to write (and export) the index function.

```r
`[.rhat` <- function (x, i, j, drop = TRUE, ...) {
  to_rhat(NextMethod())
}

# Class gets fixed
hats[-1]
#> beta[1]   alpha 
#>    1.10    1.02 
#> attr(,"class")
#> [1] "rhat"    "numeric"
sort(hats)
#> (Intercept)       alpha     beta[1] 
#>        1.00        1.02        1.10 
#> attr(,"class")
#> [1] "rhat"    "numeric"
rev(hats)
#>       alpha     beta[1] (Intercept) 
#>        1.02        1.10        1.00 
#> attr(,"class")
#> [1] "rhat"    "numeric"
```

**Comment by hadley** [comment]
I think this is now superseded by [vctrs](https://vctrs.r-lib.org). My advice would now be to use `new_vctr()` to construct your class — that way you'll get a default `[` method that preserves attributes. 

Because I don't have that much space in advanced R, I'm going to focus on how S3 works, and then leave the description of creating new classes to the vctrs documentation. The vignettes are pretty rough currently, but you can see a bunch of examples in <https://vctrs.r-lib.org/articles/s3-vector.html>
