### ISSUE TITLE
Ch. 15: minor mixup?

### ISSUE THREAD

**Issue by grasshoppermouse** [hadley/adv-r#872]
"Because the ideas that underlie R6 and RC are similar, it will only require a small amount of additional effort to learn R6 if you need to."

Do you mean:

"Because the ideas that underlie R6 and RC are similar, it will only require a small amount of additional effort to learn RC if you need to."

**Comment by hadley** [comment]
Yup. Do you want to do a PR?

**Comment by hadley** [comment]
Seems to be fixed now
