### ISSUE TITLE
8.3.1 Function factories: give examples

### ISSUE THREAD

**Issue by EdwinTh** [hadley/adv-r#879]
"
Function factories are most useful when:
- The different levels are more complex, with multiple arguments and complicated bodies.
- Some work only needs to be done once, when the function is generated.
"

I think this section could benefit from a small example of both points, to show that using closures are preferred. (Personally, I only understand the first intuitively.)

**Comment by hadley** [comment]
This is now turning into a complete chapter with an example for each use case: https://adv-r.hadley.nz/function-factories.html (still very rough)
