### ISSUE TITLE
calling.png missing binding env arrows

### ISSUE THREAD

**Issue by pkimes** [hadley/adv-r#880]
The diagram illustrating the concept of "calling environments" doesn't include arrows to show the binding environment of the functions. Not a big deal, but took a second to realize why the diagram felt different than the others.

link to diagram: https://github.com/hadley/adv-r/blob/21b6e67/diagrams/environments.png/calling.png

No idea how the original png's were made, but here's a quick mock-up in Keynote of the suggested change.
<img width="888" alt="calling-alt" src="https://user-images.githubusercontent.com/3516025/31100890-308ad4be-a799-11e7-922f-2268d7d0711b.png">

**Comment by hadley** [comment]
These diagrams are being substantially revised. I now think that figure is confusing on multiple levels.
