### ISSUE TITLE
S4 small error in smiley methods graph

### ISSUE THREAD

**Issue by Tazinho** [hadley/adv-r#883]
I think in nr. 5 a double red line is missing around the top right method/smiley. 

![s4-multiple-all](https://user-images.githubusercontent.com/11295192/31471834-1ffe8dbc-aeeb-11e7-8a7a-52f94e8713f3.png)

The correct graphic already exists and is included in the explanation 3 paragraphs above.

![s4-multiple-ambig](https://user-images.githubusercontent.com/11295192/31471897-925c4480-aeeb-11e7-9a91-eca03be482f8.png)

**Comment by hadley** [comment]
Great eyes - thanks for spotting!
