### ISSUE TITLE
S4 chapter uses "representation", which is now deprecated

### ISSUE THREAD

**Issue by andrechalom** [hadley/adv-r#884]
From setClass help page,

> representation, access, version, S3methods : _All these arguments are deprecated from version 3.0.0 of R and should be avoided_.
> ‘representation’ is an argument inherited from S that included both ‘slots’ and ‘contains’, but the use of the latter two arguments is clearer and recommended.

**Comment by hadley** [comment]
I think you must be looking at the 1st ed. It's fixed in the draft 2nd ed: https://adv-r.hadley.nz/s4.html
