### ISSUE TITLE
Section 2.2.0.1 Names bullet list not formatting correctly

### ISSUE THREAD

**Issue by ropeladder** [hadley/adv-r#903]
Bookdown doesn't include the "Or:" line or the line of code after it in the bullet list (though it looks ok in github markdown). It sits all the way over on the left, and I first read the "Or:" line and its code example as an introduction to the third way to name a vector.

```
* When creating it: `x <- c(a = 1, b = 2, c = 3)`.

* By modifying an existing vector in place: 
  `x <- 1:3; names(x) <- c("a", "b", "c")`. \indexc{names()}

  Or: 
  `x <- 1:3; names(x)[[1]] <- c("a")`. \indexc{names()}

* By creating a modified copy of a vector: 
  `x <- setNames(1:3, c("a", "b", "c"))`. \indexc{setNames()}
```

Taking out the blank line before the "Or:" line might work?

"I assign the copyright of this contribution to Hadley Wickham"

**Comment by hadley** [comment]
Can you please give a link to this section?

**Comment by ropeladder** [comment]
It looks like this is fixed now (either from a change on your end or Bookdown's). It was:
https://adv-r.hadley.nz/data-structures.html 
Section 3.3.0.1
