### ISSUE TITLE
Calls to `emo::ji()` in section "14.3.2 Multiple inheritance" not rendering smileys in html version

### ISSUE THREAD

**Issue by ramiromagno** [hadley/adv-r#905]
In the html render of S4.Rmd (https://adv-r.hadley.nz/s4.html#multiple-inheritance) the emojis are not rendered.

Code:

> What happens if methods are the same distance? For example, imagine we've defined methods for `r emo::ji("dark_sunglasses")` and `r emo::ji("slightly_smiling_face")`, and we call the generic with `r emo::ji("sunglasses")`. Note that there's no implementation for the `r emo::ji("no_mouth")` class, as indicated by the red double outline.

**Comment by hadley** [comment]
Seems to be fixed now.
