### ISSUE TITLE
example and figure doesn't match in environment chapter

### ISSUE THREAD

**Issue by dracodoc** [hadley/adv-r#908]
It seemed that there is no `edit` branch for PR now so I'm submitting issue here.

In `Environments` chapter, 

> The objects don’t live in the environment so multiple names can point to the same object:
> 
>     e$b <- e$d

![image](http://adv-r.had.co.nz/diagrams/environments.png/multiple-names.png)

I think it should be `e$a <- e$d` according to the figure. Similarly the next example 

> Confusingly they can also point to different objects that have the same value:
> 
>     e$b <- 1:3

![image 2](http://adv-r.had.co.nz/diagrams/environments.png/multiple-names.png)

should be `e$a <- 1:3`

**Comment by helix123** [comment]
I think so too.
I seems you grapped the wrong picture for the 2nd example.

**Comment by hadley** [comment]
This is fixed in the WIP 2e: https://adv-r.hadley.nz/environments.html
