### ISSUE TITLE
Write for programmers of functions more than for users of functions 

### ISSUE THREAD

**Issue by maurolepore** [hadley/adv-r#921]
Following https://github.com/hadley/adv-r/pull/919#issuecomment-345693421, here I list my suggested edits, which I had filed as a PR before -- sorry. 

(From https://adv-r.hadley.nz/oo)

* Introduction

Move readers from old to new information -- from functional to OO programming.

Previous chapters address functional programming. How about moving from old to new information by acknowledging that functional programming can get you very far but falls short in solving some particular problems -- that OO is better suited?

* Base types

Consider moving this section closer to the beginning th.

John Chambers’ pithy quote: “Everything that exists in R is an object” is familiar to many R users -- even those like me who never used OO. Thus, this material is a good candidate to move readers from old to new information. (I still believe that the first contact between readers and OO should be via functional programming (see previous comment). Following that, a second way to move readers even further may be the difference between base objects and OO.)

* OOP Systems

Consider beginning with more engaging material. 

Beginning with a dump of vocabulary and terminology seems like a way of delivering the material that is convenient for the writer but not for the reader. The risk is high that you'll lose many readers early. However, if you adapt the introduction to sufficiently motivate the readers (see my previous comment), then you'll be in a better position to present some jargon here (meaning that you may need to not change much of this sub section.)

* Focus your writing more on programmers of functions than on users of functions

This is a selfish suggestion -- I want to learn how S3 works to write functions with it. But I'll try to sell my point.

For users, S3 just works. If you write for the users of S3 functions, I guess the reaction you can expect is: "Good to know, but this won't change anything of what I already do." But if you write for the programmers of S3 functions, then the reaction could be totally different: "Wow, I'll change my approach to programming right now!". So I suggest you start with showing how you use S3. Maybe choose some functions that are very popular and not too complex. That would be something that will hook a lot of readers.

**Comment by hadley** [comment]
I'm now be certain about the scope of these OO chapters - the goal is to explain how the various OO systems work, not how to use them effectively. Obviously, it would be more useful to explain how to use them effectively, but I think that requires a book in its own right, and we still need resources that explain how S3, S4 etc work (and that's a good fit for Adv-R)
