### ISSUE TITLE
warnings absent from rendered book

### ISSUE THREAD

**Issue by jennybc** [hadley/adv-r#957]
Warnings are being suppressed and I can't tell why.

For example, here:

https://github.com/hadley/adv-r/blame/7551d617968a5c5bf106adca6230567ba050f600/S3.Rmd#L203-L208

I see the promised warning when I run the code in this chapter in isolation and when I build the book locally. But I don't see it [here](https://adv-r.hadley.nz/s3.html#constructors) (scroll to very end of this section).

**Comment by hadley** [comment]
Turns out its just this specific warning, which doesn't happen on linux. I'll insert it manually.
