### ISSUE TITLE
suggest best practices to implement better error messages

### ISSUE THREAD

**Issue by maxheld83** [hadley/adv-r#963]
(migrated from https://github.com/hadley/r-pkgs/issues/449 as suggested by @hadley)

---

I love the new [tidyverse style guide for error messages](http://style.tidyverse.org/error-messages.html), in particular the reminder to point users to the *location* of the error (e.g. the row or column index), but I'm struggling with how to best refactor existing code to achieve this (while, as far as possible, reusing existing checkmate, testthat etc. assertions).

~~I've asked over at [StackExchange](https://stackoverflow.com/questions/48591323/how-to-report-error-indices-in-r), but so far nothing much came of it. (The question really is too broad).~~
**Question now lives on [RStudio Community Forum](https://community.rstudio.com/t/implementation-best-practices-for-good-error-messages/4927), maybe there'll be a good discussion there.**

I would appreciate, if the *defensive programming* section could highlight some best practices in this regard.

I understand that this is going to depend on lots of things, won't have any *one* "best" solution and will be opinionated.

Still, to me as a relative newcomer, almost *any* kind of scaffolding is preferable to no guidelines, because it frees up cognitive capacity and keeps me from second-guessing myself. The S3 section in [adv-r](https://adv-r.hadley.nz/s3.html) was fantastic, in that regard.

Ps.: someone on twitter also brought up the question of how/whether to [accumulate multiple error messages](https://twitter.com/RussellSPierce/status/954786414201327616).

**Comment by hadley** [comment]
Done (as much as it will be for this book) in https://adv-r.hadley.nz/conditions.html#errors. This will be covered in more detail in my next book (about tidy tools)
