### ISSUE TITLE
Explaining the reasoning behind the name "quasiquotation"

### ISSUE THREAD

**Issue by anhqle** [hadley/adv-r#969]
According to the book, `quasiquotation` has two sides: `quotation` and `unquotation`.

This doesn't seem to fit with the meaning of [`quasi`](https://www.merriam-webster.com/dictionary/quasi), i.e. 

> having some resemblance usually by possession of certain attributes, e.g. a quasi corporation

Thus `quasiquotation` suggests something that is almost like quotation, but not quite. This is not the same as its intended meaning.

**Comment by david-jankoski** [comment]
This [SO discussion](https://stackoverflow.com/questions/10556631/what-is-the-meaning-of-quasi-in-quasiquotations) might shed some light on the origins and meaning.

**Comment by hadley** [comment]
I'd probably start looking in the philosophy literature (e.g. https://en.wikipedia.org/wiki/Quasi-quotation) since that's where the term arose.
