### ISSUE TITLE
obj_addr() shows different addresses for copied objects in adv-r section 4.2

### ISSUE THREAD

**Issue by cortinah** [hadley/adv-r#985]
x <- 1:3
y <- x

obj_addr(x)
#> [1] "0x4cde730"
obj_addr(y)
#> [1] "0x4b19278"

Seems to be an rmarkdown/bookdown issue

**Comment by jimhester** [comment]
Was just about to post this myself, as noted it works fine in a normal terminal.

![screenshot 2018-03-11 14 46 41](https://user-images.githubusercontent.com/205275/37257142-5e39ca62-253b-11e8-996f-1964974fa660.png)

**Comment by hadley** [comment]
It was a caching problem; fixed in 561b85e
