### ISSUE TITLE
4.2 Binding basics

### ISSUE THREAD

**Issue by jakubkuzilek** [hadley/adv-r#989]
I just find this statement, which makes me a little bit confused (addresses of objects seems different): 

> You can access the address of an object with lobstr::obj_addr(). This allows us to see that x and y both point to the same location in memory:
> 
> obj_addr(x)
> #> [1] "0x4cde730"
> obj_addr(y)
> #> [1] "0x4b19278"

Can you please explain it?

**Comment by hadley** [comment]
You're looking at an old version of the page with a bug.

**Comment by jakubkuzilek** [comment]
Brilliant :) Thank you. Was looking via the link on twitter.
