### ISSUE TITLE
Need purple box in 2nd AST

### ISSUE THREAD

**Issue by kwstat** [hadley/adv-r#990]
In Expressions.Rmd, right before this line:
`lobstr::ast(y <- x * 10)
`
there is a diagram of an AST. It looks like x is a symbol, so I wonder if the box containing the letter x should have a purple border with rounded corners (instead of the current black border with square corners)?

**Comment by hadley** [comment]
Thanks for spotting this - it turns out I messed up quite a few of these diagrams in small ways. Should be better now!
