### ISSUE TITLE
ColSums vs sapply and apply functions

### ISSUE THREAD

**Issue by gbouzill** [hadley/adv-r#996]
On a data.frame, using sapply(df, sum) is much faster than using colSums (tested with microbenchmark on a dataframe of 1,000 rows and 10,000 columns).
On the opposite apply(df, 2, sum) is slower.

Is there any reason to explain these performances ? I tought colSums would have been faster on all situations ?

Maybe the Vectorise section could benefit of more details on these aspects ?

Thank you very much,

**Comment by hadley** [comment]
Because `apply()` and `colSums()` always coerce to a matrix first.
